routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "dashboard" middleware group and "App\Http\Controllers\Dashboard" namespace.
| and "dashboard." route's alias name. Enjoy building your dashboard!
|
*/

Route::get('/', 'DashboardController@index')->name('home');

// Select All Routes.
Route::delete('delete', 'DeleteController@destroy')->name('delete.selected');
Route::delete('forceDelete', 'DeleteController@forceDelete')->name('forceDelete.selected');
Route::delete('restore', 'DeleteController@restore')->name('restore.selected');

// Select All Routes.
Route::get('export', 'ExcelController@export')->name('excel.export');
Route::post('import', 'ExcelController@import')->name('excel.import');


// Customers Routes.
Route::get('trashed/customers', 'CustomerController@trashed')->name('customers.trashed');
Route::get('trashed/customers/{trashed_customer}', 'CustomerController@showTrashed')->name('customers.trashed.show');
Route::post('customers/{trashed_customer}/restore', 'CustomerController@restore')->name('customers.restore');
Route::delete('customers/{trashed_customer}/forceDelete', 'CustomerController@forceDelete')->name('customers.forceDelete');
Route::resource('customers', 'CustomerController');

// Supervisors Routes.
Route::get('trashed/supervisors', 'SupervisorController@trashed')->name('supervisors.trashed');
Route::get('trashed/supervisors/{trashed_supervisor}', 'SupervisorController@show')->name('supervisors.trashed.show');
Route::post('supervisors/{trashed_supervisor}/restore', 'SupervisorController@restore')->name('supervisors.restore');
Route::delete('supervisors/{trashed_supervisor}/forceDelete', 'SupervisorController@forceDelete')->name('supervisors.forceDelete');
Route::resource('supervisors', 'SupervisorController');

// Admins Routes.
Route::get('trashed/admins', 'AdminController@trashed')->name('admins.trashed');
Route::get('trashed/admins/{trashed_admin}', 'AdminController@show')->name('admins.trashed.show');
Route::post('admins/{trashed_admin}/restore', 'AdminController@restore')->name('admins.restore');
Route::delete('admins/{trashed_admin}/forceDelete', 'AdminController@forceDelete')->name('admins.forceDelete');
Route::resource('admins', 'AdminController');

// Settings Routes.
Route::get('settings', 'SettingController@index')->name('settings.index');
Route::patch('settings', 'SettingController@update')->name('settings.update');
Route::get('backup/download', 'SettingController@downloadBackup')->name('backup.download');

// Feedback Routes.
Route::patch('feedback/read', 'FeedbackController@read')->name('feedback.read');
Route::patch('feedback/unread', 'FeedbackController@unread')->name('feedback.unread');
Route::resource('feedback', 'FeedbackController')->only('index', 'show', 'destroy');


        Route::get('trashed/categories', 'CategoryController@trashed')->name('categories.trashed');
        Route::get('trashed/categories/{trashed_category}', 'CategoryController@showTrashed')->name('categories.trashed.show');
        Route::post('categories/{trashed_category}/restore', 'CategoryController@restore')->name('categories.restore');
        Route::delete('categories/{trashed_category}/forceDelete', 'CategoryController@forceDelete')->name('categories.forceDelete');
        Route::resource('categories', 'CategoryController');


        Route::get('trashed/roles', 'RoleController@trashed')->name('roles.trashed');
        Route::get('trashed/roles/{trashed_role}', 'RoleController@showTrashed')->name('roles.trashed.show');
        Route::post('roles/{trashed_role}/restore', 'RoleController@restore')->name('roles.restore');
        Route::delete('roles/{trashed_role}/forceDelete', 'RoleController@forceDelete')->name('roles.forceDelete');
        Route::resource('roles', 'RoleController');



        Route::get('trashed/branches', 'BranchController@trashed')->name('branches.trashed');
        Route::get('trashed/branches/{trashed_branch}', 'BranchController@showTrashed')->name('branches.trashed.show');
        Route::post('branches/{trashed_branch}/restore', 'BranchController@restore')->name('branches.restore');
        Route::delete('branches/{trashed_branch}/forceDelete', 'BranchController@forceDelete')->name('branches.forceDelete');
        Route::resource('branches', 'BranchController');

        Route::get('trashed/categories', 'CategoryController@trashed')->name('categories.trashed');
        Route::get('trashed/categories/{trashed_category}', 'CategoryController@showTrashed')->name('categories.trashed.show');
        Route::post('categories/{trashed_category}/restore', 'CategoryController@restore')->name('categories.restore');
        Route::delete('categories/{trashed_category}/forceDelete', 'CategoryController@forceDelete')->name('categories.forceDelete');
        Route::resource('categories', 'CategoryController');

        Route::get('trashed/cars', 'CarController@trashed')->name('cars.trashed');
        Route::get('trashed/cars/{trashed_car}', 'CarController@showTrashed')->name('cars.trashed.show');
        Route::post('cars/{trashed_car}/restore', 'CarController@restore')->name('cars.restore');
        Route::delete('cars/{trashed_car}/forceDelete', 'CarController@forceDelete')->name('cars.forceDelete');
        Route::resource('cars', 'CarController');

        Route::get('trashed/manufactories', 'ManufactoryController@trashed')->name('manufactories.trashed');
        Route::get('trashed/manufactories/{trashed_manufactory}', 'ManufactoryController@showTrashed')->name('manufactories.trashed.show');
        Route::post('manufactories/{trashed_manufactory}/restore', 'ManufactoryController@restore')->name('manufactories.restore');
        Route::delete('manufactories/{trashed_manufactory}/forceDelete', 'ManufactoryController@forceDelete')->name('manufactories.forceDelete');
        Route::resource('manufactories', 'ManufactoryController');

        Route::get('trashed/sliders', 'SliderController@trashed')->name('sliders.trashed');
        Route::get('trashed/sliders/{trashed_slider}', 'SliderController@showTrashed')->name('sliders.trashed.show');
        Route::post('sliders/{trashed_slider}/restore', 'SliderController@restore')->name('sliders.restore');
        Route::delete('sliders/{trashed_slider}/forceDelete', 'SliderController@forceDelete')->name('sliders.forceDelete');
        Route::resource('sliders', 'SliderController');

        Route::get('trashed/orders', 'OrderController@trashed')->name('orders.trashed');
        Route::get('trashed/orders/{trashed_order}', 'OrderController@showTrashed')->name('orders.trashed.show');
        Route::post('orders/{trashed_order}/restore', 'OrderController@restore')->name('orders.restore');
        Route::delete('orders/{trashed_order}/forceDelete', 'OrderController@forceDelete')->name('orders.forceDelete');
        Route::resource('orders', 'OrderController');
/*  The routes of generated crud will set here: Don't remove this line  */
        
        
        
        
        
        

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('dashboard.locales')->group(function () {
    Auth::routes();
});

Route::impersonate();
Route::get('locale/{locale}', 'LocaleController@update')->name('locale')->where('locale', '(ar|en)');

// Route::get('/', function () {
//     dd(Request()->all());
//     return view('welcome');
// });

Route::get('/getCarsCategories', 'Web\SiteController@getCarsCategories');

Route::as('front.')->group(function () {
    Route::get('/', 'Frontend\FrontendController@index')->name('main');
    Route::get('/fleet', 'Frontend\FrontendController@fleet')->name('fleet');
    Route::get('/booking', 'Frontend\FrontendController@booking')->name('booking');
    Route::get('/branches', 'Frontend\FrontendController@branches')->name('branches');
    Route::get('/contactus', 'Frontend\FrontendController@contactus')->name('contactus');
    Route::get('/employment', 'Frontend\FrontendController@employment')->name('employment');
    Route::get('/profile', function(){
        return view('frontend.profile');
    })->name('profile');
    // Route::get('/register', function(){
    //     return view('frontend.register');
    // })->name('register.index');
});

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Category;
use Illuminate\Routing\Controller;
use App\Http\Resources\SelectResource;
use App\Http\Resources\CategoryResource;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class CategoryController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    /**
     * Display a listing of the categories.
     * @OA\Get(
     *      path="/categories",
     *      operationId="getCategoriesList",
     *      tags={"Categories"},
     *      summary="Get list of categories",
     *      description="Returns list of categories",
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *          @OA\JsonContent(ref="#/components/schemas/CategoryResource")
     *       ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     * )
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index()
    {
        $categories = Category::filter()->simplePaginate();
        return CategoryResource::collection($categories);
    }

    /**
     * Display the specified category.
     *
     * @OA\Get(
     *      path="/categories/{id}",
     *      operationId="getCategoryById",
     *      tags={"Categories"},
     *      summary="Get category information",
     *      description="Returns category data",
     *      @OA\Parameter(
     *          name="id",
     *          description="Category id",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="integer"
     *          )
     *      ),
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *           @OA\JsonContent(ref="#/components/schemas/Category")
     *
     *       ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      ),
     *      @OA\Response(
     *          response=404,
     *          description="Not Found"
     *      )
     * )
     * @param \App\Models\Category $category
     * @return \App\Http\Resources\CategoryResource
     */
    public function show(Category $category)
    {
        return new CategoryResource($category);
    }

    /**
     * Display a listing of the resource.
    * @OA\Get(
     *      path="/select/categories",
     *      operationId="getSelectCategoriesList",
     *      tags={"Categories"},
     *      summary="Get list of Select categories",
     *      description="Returns list of Select categories",
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *          @OA\JsonContent(ref="#/components/schemas/CategoryResource")
     *       ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     * )
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function select()
    {
        $categories = Category::filter()->simplePaginate();

        return SelectResource::collection($categories);
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Admin;
use Illuminate\Routing\Controller;
use App\Http\Requests\Dashboard\AdminRequest;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class AdminController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    /**
     * AdminController constructor.
     *
     */
    public function __construct()
    {
        $this->authorizeResource(Admin::class, 'admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = Admin::filter()->paginate();

        return view('dashboard.accounts.admins.index', compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.accounts.admins.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Dashboard\AdminRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(AdminRequest $request)
    {
        $admin = Admin::create($request->allWithHashedPassword());

        $admin->setType($request->type);

        $admin->addAllMediaFromTokens();

        flash(trans('admins.messages.created'));

        return redirect()->route('dashboard.admins.show', $admin);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Admin $admin
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        return view('dashboard.accounts.admins.show', compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Admin $admin
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $admin)
    {
        return view('dashboard.accounts.admins.edit', compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Dashboard\AdminRequest $request
     * @param \App\Models\Admin $admin
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(AdminRequest $request, Admin $admin)
    {
        $admin->update($request->allWithHashedPassword());

        $admin->setType($request->type);

        $admin->addAllMediaFromTokens();

        flash(trans('admins.messages.updated'));

        return redirect()->route('dashboard.admins.show', $admin);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Admin $admin
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Admin $admin)
    {
        $admin->delete();

        flash(trans('admins.messages.deleted'));

        return redirect()->route('dashboard.admins.index');
    }

    /**
     * Display a listing of the trashed resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function trashed()
    {
        $this->authorize('viewTrash', Admin::class);

        $admins = Admin::onlyTrashed()->paginate();

        return view('dashboard.accounts.admins.trashed', compact('admins'));
    }

    /**
     * Display the specified trashed resource.
     *
     * @param \App\Models\Admin $admin
     * @return \Illuminate\Http\Response
     */
    public function showTrashed(Admin $admin)
    {
        return view('dashboard.accounts.admins.show', compact('admin'));
    }

    /**
     * Restore the trashed resource.
     *
     * @param \App\Models\Admin $admin
     * @return \Illuminate\Http\RedirectResponse
     */
    public function restore(Admin $admin)
    {
        $this->authorize('restore', $admin);

        $admin->restore();

        flash()->success(trans('admins.messages.restored'));

        return redirect()->route('dashboard.admins.trashed');
    }

    /**
     * Force delete the specified resource from storage.
     *
     * @param \App\Models\Admin $admin
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function forceDelete(Admin $admin)
    {
        $this->authorize('forceDelete', $admin);

        $admin->forceDelete();

        flash(trans('admins.messages.deleted'));

        return redirect()->route('dashboard.admins.trashed');
    }
}

app/View/Components/Layout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Layout extends Component
{
    /**
     * @var string
     */
    public $title;

    /**
     * @var array
     */
    public $breadcrumbs = [];

    /**
     * Create a new component instance.
     *
     * @param null $title
     * @param array $breadcrumbs
     */
    public function __construct($title = null, $breadcrumbs = [])
    {
        $this->title = $title;
        $this->breadcrumbs = $breadcrumbs;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('dashboard::master');
    }
}

resources/views/dashboard/categories/create.blade.php
<x-layout :title="trans('categories.actions.create')" :breadcrumbs="['dashboard.categories.create']">
    {{ BsForm::resource('categories')->post(route('dashboard.categories.store')) }}
    @component('dashboard::components.box')
        @slot('title', trans('categories.actions.create'))

        @include('dashboard.categories.partials.form')

        @slot('footer')
            {{ BsForm::submit()->label(trans('categories.actions.save')) }}
        @endslot
    @endcomponent
    {{ BsForm::close() }}
</x-layout>

resources/views/dashboard/categories/edit.blade.php
<x-layout :title="$category->name" :breadcrumbs="['dashboard.categories.edit', $category]">
    {{ BsForm::resource('categories')->putModel($category, route('dashboard.categories.update', $category)) }}
    @component('dashboard::components.box')
        @slot('title', trans('categories.actions.edit'))

        @include('dashboard.categories.partials.form')

        @slot('footer')
            {{ BsForm::submit()->label(trans('categories.actions.save')) }}
        @endslot
    @endcomponent
    {{ BsForm::close() }}
</x-layout>

resources/views/dashboard/categories/index.blade.php
<x-layout :title="trans('categories.plural')" :breadcrumbs="['dashboard.categories.index']">
    @include('dashboard.categories.partials.filter')

    @component('dashboard::components.table-box')
        @slot('title')
            @lang('categories.actions.list') ({{ $categories->total() }})
        @endslot

        <thead>
        <tr>
          <th colspan="100">
            <div class="d-flex">
                <x-check-all-delete
                    type="{{ \App\Models\Category::class }}"
                    :resource="trans('categories.plural')"></x-check-all-delete>
                <x-import-excel
                            model="{{ \App\Models\Category::class }}"
                            import="{{ \App\Imports\CategoriesImport::class }}"
                            exportResource="{{ App\Http\Resources\CategoryResource::class }}"
                            :resource="trans('categories.plural')"></x-import-excel>
                <x-export-excel
                            model="{{ \App\Models\Category::class }}"
                            export="{{ \App\Exports\Export::class }}"
                            resource="{{ App\Http\Resources\CategoryResource::class }}"
                            fileName="Categories"
                            ></x-export-excel>
                <div class="ml-2 d-flex justify-content-between flex-grow-1">
                    @include('dashboard.categories.partials.actions.create')
                    @include('dashboard.categories.partials.actions.trashed')
                </div>
            </div>
          </th>
        </tr>
        <tr>
            <th style="width: 30px;" class="text-center">
              <x-check-all></x-check-all>
            </th>
            <th>@lang('categories.attributes.name')</th>
            <th>@lang('categories.attributes.orderBy_numper')</th>
            <th>@lang('categories.attributes.vat')</th>
            <th>@lang('categories.attributes.created_at')</th>
            <th style="width: 160px">...</th>
        </tr>
        </thead>
        <tbody>
        @forelse($categories as $category)
            <tr>
                <td class="text-center">
                  <x-check-all-item :model="$category"></x-check-all-item>
                </td>
                <td>
                    <a href="{{ route('dashboard.categories.show', $category) }}"
                       class="text-decoration-none text-ellipsis">
                        {{ $category->name }}
                    </a>
                </td>
                <td>{{ $category->orderBy_numper}}</td>
                <td>{{ $category->vat}}</td>
                <td>{{ $category->created_at->format('Y-m-d') }}</td>

                <td style="width: 160px">
                    @include('dashboard.categories.partials.actions.show')
                    @include('dashboard.categories.partials.actions.edit')
                    @include('dashboard.categories.partials.actions.delete')
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="100" class="text-center">@lang('categories.empty')</td>
            </tr>
        @endforelse

        @if($categories->hasPages())
            @slot('footer')
                {{ $categories->links() }}
            @endslot
        @endif
    @endcomponent
</x-layout>

resources/views/dashboard/categories/show.blade.php
<x-layout :title="$category->name" :breadcrumbs="['dashboard.categories.show', $category]">
    <div class="row">
        <div class="col-md-6">
            @component('dashboard::components.box')
                @slot('class', 'p-0')
                @slot('bodyClass', 'p-0')

                <table class="table table-striped table-middle">
                    <tbody>
                    <tr>
                        <th width="200">@lang('categories.attributes.name')</th>
                        <td>{{ $category->name }}</td>
                    </tr>
                    <tr>
                        <th width="200">@lang('categories.attributes.orderBy_numper')</th>
                        <td>{{ $category->orderBy_numper }}</td>
                    </tr>
                    <tr>
                        <th width="200">@lang('categories.attributes.vat')</th>
                        <td>{{ $category->vat }}</td>
                    </tr>
                    {{-- @if($category->getFirstMedia())
                        <tr>
                            <th width="200">@lang('categories.attributes.image')</th>
                            <td>
                                <file-preview :media="{{ $category->getMediaResource() }}"></file-preview>
                            </td>
                        </tr>
                    @endif --}}
                    </tbody>
                </table>

                @slot('footer')
                    @include('dashboard.categories.partials.actions.edit')
                    @include('dashboard.categories.partials.actions.delete')
                @endslot
            @endcomponent
        </div>
    </div>
</x-layout>

resources/views/dashboard/categories/trashed.blade.php
<x-layout :title="trans('categories.trashed')" :breadcrumbs="['dashboard.categories.trashed']">
    @include('dashboard.categories.partials.filter')

    @component('dashboard::components.table-box')

        @slot('title')
            @lang('categories.actions.list') ({{ count_formatted($categories->total()) }})
        @endslot

        <thead>
        <tr>
            <th colspan="100">
                <x-check-all-force-delete
                        type="{{ \App\Models\Category::class }}"
                        :resource="trans('categories.plural')"></x-check-all-force-delete>
                <x-check-all-restore
                        type="{{ \App\Models\Category::class }}"
                        :resource="trans('categories.plural')"></x-check-all-restore>
            </th>
        </tr>
        <tr>
            <th>
                <x-check-all></x-check-all>
            </th>
            <th>@lang('categories.attributes.name')</th>
            <th>@lang('categories.attributes.deleted_at')</th>
            <th style="width: 160px">...</th>
        </tr>
        </thead>
        <tbody>
        @forelse($categories as $category)
            <tr>
                <td class="text-center">
                  <x-check-all-item :model="$category"></x-check-all-item>
                </td>
                    <td>
                    <a href="{{ route('dashboard.categories.show', $category) }}"
                       class="text-decoration-none text-ellipsis">

                        {{-- <img src="{{ $category->getFirstMediaUrl() }}"
                             alt="Product 1"
                             class="img-circle img-size-32 mr-2" style="height: 32px;"> --}}
                        {{ $category->name }}
                    </a>
                </td>

                <td>{{ $category->orderBy_numper }}</td>
                <td>{{ $category->vat }}</td>
                <td>{{ $category->deleted_at->format('Y-m-d') }}</td>

                <td style="width: 160px">
                    @include('dashboard.categories.partials.actions.show')
                    @include('dashboard.categories.partials.actions.restore')
                    @include('dashboard.categories.partials.actions.forceDelete')
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="100" class="text-center">@lang('categories.empty')</td>
            </tr>
        @endforelse

        @if($categories->hasPages())
            @slot('footer')
                {{ $categories->links() }}
            @endslot
        @endif
    @endcomponent
</x-layout>